"""matchmaking and looks

Revision ID: 965a078fa607
Revises: fd16e85b766b
Create Date: 2026-08-09 21:50:28.002872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965a078fa607'
down_revision: Union[str, Sequence[str], None] = 'fd16e85b766b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('looks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('looks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_looks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_looks_user_id'), ['user_id'], unique=False)

    op.create_table('look_items',
    sa.Column('look_id', sa.Integer(), nullable=False),
    sa.Column('cloth_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cloth_id'], ['clothes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['look_id'], ['looks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('look_id', 'cloth_id')
    )
    op.create_table('matching_clothes',
    sa.Column('cloth_id', sa.Integer(), nullable=False),
    sa.Column('matched_cloth_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cloth_id'], ['clothes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_cloth_id'], ['clothes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cloth_id', 'matched_cloth_id')
    )
    # NOTE: autogenerate also flagged ix_clothes_category/color/season as "added" —
    # that's pre-existing drift on this dev db (missing since baseline), unrelated
    # to Milestone 5, and intentionally left out of this revision.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matching_clothes')
    op.drop_table('look_items')
    with op.batch_alter_table('looks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_looks_user_id'))
        batch_op.drop_index(batch_op.f('ix_looks_id'))

    op.drop_table('looks')
    # ### end Alembic commands ###
