"""baseline

Revision ID: fd16e85b766b
Revises: 
Create Date: 2026-08-09 18:43:53.462876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd16e85b766b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('is_oversize', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clothes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothes_color'), ['color'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothes_season'), ['season'], unique=False)

    op.create_table('wear_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloth_id', sa.Integer(), nullable=False),
    sa.Column('worn_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cloth_id'], ['clothes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloth_id', 'worn_date', name='uq_cloth_worn_date')
    )
    with op.batch_alter_table('wear_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wear_logs_cloth_id'), ['cloth_id'], unique=False)
        batch_op.create_index('ix_wear_logs_cloth_worn', ['cloth_id', 'worn_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_wear_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wear_logs_worn_date'), ['worn_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wear_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wear_logs_worn_date'))
        batch_op.drop_index(batch_op.f('ix_wear_logs_id'))
        batch_op.drop_index('ix_wear_logs_cloth_worn')
        batch_op.drop_index(batch_op.f('ix_wear_logs_cloth_id'))

    op.drop_table('wear_logs')
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clothes_season'))
        batch_op.drop_index(batch_op.f('ix_clothes_id'))
        batch_op.drop_index(batch_op.f('ix_clothes_color'))
        batch_op.drop_index(batch_op.f('ix_clothes_category'))

    op.drop_table('clothes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
